
package transducer;

/**
 * Events that the transducer can fire
 */
public enum TEvent
{
	// global events
	START,
	STOP,
	SET_RECIPE,

	// conveyor
	CONVEYOR_DO_START,
	CONVEYOR_DO_STOP,
	
	CONVEYOR_DO_BREAK,
	CONVEYOR_DO_FIX,
	CONVEYOR_BROKEN,
	CONVEYOR_FIXED,

	// sensor
	SENSOR_GUI_PRESSED,
	SENSOR_GUI_RELEASED,

	// popup
	POPUP_DO_MOVE_UP,
	POPUP_GUI_MOVED_UP,
	POPUP_DO_MOVE_DOWN,
	POPUP_GUI_MOVED_DOWN,
	POPUP_RELEASE_GLASS,
	POPUP_GUI_LOAD_FINISHED,
	POPUP_GUI_RELEASE_FINISHED,
	
	POPUP_DO_BREAK,
	POPUP_DO_FIX,
	POPUP_BROKEN,
	POPUP_FIXED,

	// truck
	TRUCK_DO_LOAD_GLASS,
	TRUCK_GUI_LOAD_FINISHED,
	TRUCK_DO_EMPTY,
	TRUCK_GUI_EMPTY_FINISHED,
	
	TRUCK_DO_BREAK,
	TRUCK_DO_FIX,
	TRUCK_BROKEN,
	TRUCK_FIXED,

	// workstations
	WORKSTATION_DO_ACTION,
	WORKSTATION_RELEASE_GLASS,
	WORKSTATION_GUI_ACTION_FINISHED,
	WORKSTATION_DO_LOAD_GLASS,
	WORKSTATION_LOAD_FINISHED,
	WORKSTATION_RELEASE_FINISHED,
	
	WORKSTATION_DO_BREAK,
	WORKSTATION_DO_FIX,
	WORKSTATION_BROKEN,
	WORKSTATION_FIXED,
	
	WORKSTATION_DO_BREAK_GLASS_DURING_MACHINING,
	WORKSTATION_GLASS_BROKEN_DURING_MACHINING,
	
	//bin and "Glass Ghosts"
	BIN_CREATE_PART,
	BIN_PART_CREATED,
	
}
